   ; This is a comment - comments start with a semicolon
[owner]
name = John Doe
organization = Acme Widgets Inc.

[database]
; Use IP address if network name resolution is not working
server = 192.0.2.62
port = 143
file = "payroll.dat"
